# ======
project.name=lab3
project.version=1.0
main.class=org.coordinate.service.AreaCheck

# ======
src.dir=src/main/java
resources.dir=src/main/resources
webapp.dir=src/main/webapp
test.src.dir=test/java

build.dir=build.ant
classes.dir=${build.dir}/classes
dist.dir=${build.dir}/dist
test.classes.dir=${build.dir}/test-classes
test.reports.dir=${build.dir}/test-reports
javadoc.dir=${build.dir}/javadoc
team.dir=${build.dir}/team

# ======
lib.dir=lib

# ======
java.source=11
java.target=11
encoding=UTF-8

# === SVN  ===
svn.repo.url=file:///C:/svn-repos/lab3
svn.username=student
svn.password=student123

# === Git  ===
git.repo=.
git.diff.output=${build.dir}/last-working-diff.patch

# =====
jar.file=${project.name}-${project.version}.jar
team.zip.file=${project.name}-team-revisions.zip